---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  interval: 5m0s
  url: https://vadimkim.github.io/cert-manager-webhook-hetzner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      version: "<1.3.4"
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-hetzner
        namespace: cert-manager
      interval: 1m
  values:
    groupName: dns.hetzner
