---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: networking
spec:
  interval: 1m0s
  ref:
    tag: v1.4.0
  url: https://github.com/kubernetes-sigs/gateway-api.git
  ignore: |
    # Only include the thick daemonset
    /*
    !/config/crd/standard/*
    !/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-standard
  namespace: networking
spec:
  interval: 10m0s
  path: ./config/crd/standard
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-experimental
  namespace: networking
spec:
  interval: 10m0s
  path: ./config/crd/experimental
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api
