---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: multus-cni
  namespace: networking
spec:
  interval: 1m0s
  ref:
    tag: v4.2.3
  url: https://github.com/k8snetworkplumbingwg/multus-cni.git
  ignore: |
    # Only include the thick daemonset
    /*
    !/deployments/multus-daemonset-thick.yml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus-cni
  namespace: networking
spec:
  interval: 10m0s
  path: ./deployments
  prune: true
  sourceRef:
    kind: GitRepository
    name: multus-cni
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          name: kube-mutlus-ds
          namespace: kube-system
        spec:
          template:
            spec:
              volumes:
                - name: host-run-netns
                  hostPath:
                    path: /var/run/netns/
      target:
        kind: DaemonSet
        name: kube-multus-ds
        namespace: kube-system
