# manifests/infrastructure/external-dns/hetzner-token.yaml
apiVersion: v1
data:
    HETZNER_TOKEN: ENC[AES256_GCM,data:9KriEPHoxG14pJX67mgbdKd8dYlyB3+1MgCHWkgiKFsjhGyXqitKx/F00ZA=,iv:G52II8qetasavLrdFuGfusVr0zWx770Vb4eqN7EBuhw=,tag:w/3TjeAdwD1b4Fg2h+dt5w==,type:str]
kind: Secret
metadata:
    name: hetzner-token
    namespace: external-dns
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-24T12:30:54Z"
    mac: ENC[AES256_GCM,data:PnF/fidJ5eqvHgGvEXFDgRxYQmNDbkA+buHNDBHpSuYN0/NWI6PzZYsBrNkpDeyheYIIoOOxIQDKC0hHSW9wAgqAPOzBS22bZjXORzLnoZtf1INdDuVrt86FvxZks5RIoXc4KNlHM7DP5Ny2krvxrKStrLJb7uHrymfWuy1Ij60=,iv:lS58WtrgtJ6LPv7EVMdAq9xdjRqxHNFp8++83VgCqD8=,tag:VQF4RDQCKz0m0kORFUsNhw==,type:str]
    pgp:
        - created_at: "2023-06-24T12:30:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DO8XyRaEk3R4SAQdAyvCjBAM3ppt49KitmLJ5wQDvjipiZ+EyzMNU4uM4r2cw
            /dX3vEzPbw+V6HMKPURh12dh0u0MqhqjlujnkqUuwnOAAt4OxAp/7pTSgRv4B0sA
            0l4BLDnWBowsfyByP23kHYaHq3a5WwkdVsAACoGmAJjAUQ/eWN8BS8CQLDETRYcw
            p9UKlUppuqsmMqir2/pyiV72aFmrPoafqB4Q0wmVPqefOQqGgrbthRKUrhabxX7H
            =Od79
            -----END PGP MESSAGE-----
          fp: BD995FEE3775172B56BF652CF10FF7F3F7265919
        - created_at: "2023-06-24T12:30:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4Dw5+PhuNaN4USAQdAgwrFcjGqyQOI96x1U5todJGD073zFSQVSap6/USP52Qw
            QYZFqQn9uDU7oDZEv4+WYCyUD6jDEpAS+KSs+iwtbvrzfw8evs7bliLfEwE8pE9m
            0l4B2N1SZExRcZRiH390eI/zb/3losNoe9ouMVRdinAXBdUQ+nivknugO6yHsNmQ
            CjZtbs4udNn5lJjyGzpRLGbY3vK1P3qZTOmeLEn3RaoMw1CiQRAWYC13qnTGt3vp
            =E0NJ
            -----END PGP MESSAGE-----
          fp: 7668061D49BB2B7BA19118B4031734BEBE51F818
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
