# manifests/infrastructure/cert-manager/cert-manager.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: ">=v3.9.0 <3.10.0"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: kube-system
      interval: 1m
  values:
    apiService:
      insecureSkipTLSVerify: true
