# manifests/cluster/flux-system/metrics-server.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kamaji
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/infrastructure/kamaji
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
