# manifests/cluster/flux-system/kubelet-cert-rotation.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    semver: ">=0.7.0 < 0.8.0"
  secretRef:
    name: flux-system
  url: ssh://git@github.com/alex1989hu/kubelet-serving-cert-approver
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./deploy/standalone
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubelet-serving-cert-approver
