# manifests/cluster/flux-system/kubevirt.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/infrastructure/kubevirt
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kubevirt
---