# manifests/cluster/flux-system/openobserve.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openobserve
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/infrastructure/openobserve
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
