apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pointclap-namespace
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/pointclap/namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pointclap-teamspeak3
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/pointclap/teamspeak3
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: pointclap
  dependsOn:
    - name: pointclap-namespace
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pointclap-7daystodie
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/pointclap/7daystodie
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: pointclap
  dependsOn:
    - name: pointclap-namespace
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pointclap-factorio
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/pointclap/factorio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: pointclap
  dependsOn:
    - name: pointclap-namespace
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pointclap-zomboid
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/pointclap/zomboid
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: pointclap
  dependsOn:
    - name: pointclap-namespace
