apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pointclap-namespace
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/pointclap/namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pointclap-external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/pointclap/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: pointclap
  dependsOn:
  - name: pointclap-namespace
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pointclap-teamspeak3
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/pointclap/teamspeak3
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: pointclap
  dependsOn:
  - name: pointclap-namespace
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
