apiVersion: v1
kind: Secret
metadata:
    name: zomboid-secrets
    namespace: pointclap
stringData:
    admin-password: ENC[AES256_GCM,data:rFAJT8tS,iv:KsoXwlrggaZMGF6r72TkmANnYHL16EQcmEtlVZSLN64=,tag:mMtAkg0TbuUE2PZKKXllDA==,type:str]
    server-password: ENC[AES256_GCM,data:zCUfXjeG,iv:jm8kWG2kqhwBRg3OGH1D5rxDMI2SmNII9klFvNP5VI4=,tag:+8nx+RDxuTJVRl+zfQVh/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeUV4KzdZa1QyZlk3bVAv
            anpsMXI2NEQ1bjZSeERsT2VFSUt3am82ZVJrCllyekNWZENJOXQ4MFNQTzBWZXR1
            MVNxK05KZXg4cFlUSkh4SVBFSk5tMFEKLS0tIGozcDhxS0o4dXZ1Z2FvTndEVEpy
            cWVydUM3QXBjd1dxSnZSd3JYTnN2MWcKOJNUNoULBkyVK15gEmjaf/qj89Ys6K1k
            tdqDsgTytbM4DR/adZpw9MDbx45mgGFtiZlLelgHejCwnSdhsAw5zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCY0JpdnhpNjVYREg3TFhs
            M1k1S0U0NUFNMHZHNlh2eENRbk5hdVFsb0NjCkRpanJSMmorc1JhRUFvZFZSdWZR
            RE02ejU1U1NIWW1qazhNTllaRnBiSUkKLS0tIHZrL0czd0RETHh2SVBQYWhqM2dE
            eGpIRzJsUUNwYkpLWlZiRTJQeWs4RUkKTfvdhJy/zc1JGX/umoFeFXxF91geNnnU
            Cr025y4Wi8/mNYrqvnGQcI6O80aRh8fYnn9YC6PnH6Dcit9YjNPxqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T09:23:38Z"
    mac: ENC[AES256_GCM,data:mYzm8R1++E8pv80EgkRi32KOQ520Q6tgLMUZDCM2a75UxJBInlVXbGYm4hlajZjbiyTBSkQfV80IsZWnZx/8It91ZuGGCvNZXEzuOAgdVG0wx4ULmXDF+MlwoPrb+qUdBeyd8W4jkqpmzr1SZmTE9jvF0dDR9/EeHOnqyP/HjIc=,iv:hMHDWVu84S996YwuRADXlVOdbfT6uRHSeW+lO2UFuy0=,tag:Fq8chsvNMv7Edz224kMq6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|Authorization)$
    version: 3.9.1
