apiVersion: v1
kind: Service
metadata:
  name: zomboid-pzserver
  namespace: pointclap
spec:
  ports:
    - name: pzserver
      nodePort: 30914
      port: 30914
      protocol: UDP
      targetPort: pzserver
    - name: pzplayer
      nodePort: 30915
      port: 30915
      protocol: UDP
      targetPort: pzplayer
  selector:
    app: pzserver
  type: NodePort
