# manifests/infrastructure/harbor-registry/admin-password.yaml
apiVersion: v1
data:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:3/Xg0LFxMa+SdplifVYQcqeCsbjxtRHUzBM2v5H3oDk2ie+KIGWMGlgytSU=,iv:q0EXbUWWbj9ShMuAHAAeDd1pwuUSJsI0y4okQkanRRM=,tag:s5GyD/Ehk1yuy+7izogM4A==,type:str]
kind: Secret
metadata:
    name: harbor-admin-password
    namespace: harbor-registry
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaVNEdUVqeFdNU2RIekJH
            MGdsTXB2ZGNLZEpvUE5NdWs4UUdiSWhCRHc0CldYckU1dTRuem16M3dCSU5JckJJ
            OHg0c3VzT2dwdkx4TCthM3JJeWhMQ3MKLS0tIG50UUdPcUl4RlYxRExsMVJuNncx
            WUE2KzlabHk5czQ5TThLTWcwRWxQZ1EK4AGo2HZJ/zmy8A+0kAw5jYsI0m+Z8lvT
            n6tA3zTY6fEaj5+Z52SXo5wDCMqP5QcH+CzchU6kD7/9pA/y5OAbJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bGdPUGZ6bTlFdDB6MzBO
            YW9NNi9nc25sMGdJbjFwWVdMT1d5eXVGZDJzCjgvS2tXVzRYRjExM1NQRHRMdlVx
            dE9jYWRuK3UwZ1hnM1BXb3owMGpSZU0KLS0tIFIzLzUrank3VXJ5R0Nhci9Zdk9V
            U1JRYWwxY1ZkcnFrWDFSZEh2d1pWbWMKi3GLCREcoOG8RfUnsgm13vgen5jb3ezR
            y67Ffle9sHe9yYjogWWxTK/szh+zha4PZSjnXInpV81pY4QlIUgr/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T12:47:00Z"
    mac: ENC[AES256_GCM,data:s3RG782jXqYcKS/JkL0b2TRpXpxRwOP2VQgP2vNN/c8q+di2QmElBtGCWC+1qBXCOhdZXShZjUDpdD85qTJY3wvbpyHGQyAjsMgorVx1J2aHVIY2JYf22SiecGDR6h6QI149NJ4ix5bffhm6rFpd/UycEz9pGoQgYI97KKe+fqM=,iv:TwMR4KeXsLgWAg5E8S2mBNxkiTWBM/vCCPjGpWbfHLA=,tag:9IawtvC1DA31zGoyDpiDIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
