# manifests/infrastructure/harbor-registry/admin-password.yaml
apiVersion: v1
data:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:3/Xg0LFxMa+SdplifVYQcqeCsbjxtRHUzBM2v5H3oDk2ie+KIGWMGlgytSU=,iv:q0EXbUWWbj9ShMuAHAAeDd1pwuUSJsI0y4okQkanRRM=,tag:s5GyD/Ehk1yuy+7izogM4A==,type:str]
kind: Secret
metadata:
    name: harbor-admin-password
    namespace: harbor-registry
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-27T12:47:00Z"
    mac: ENC[AES256_GCM,data:s3RG782jXqYcKS/JkL0b2TRpXpxRwOP2VQgP2vNN/c8q+di2QmElBtGCWC+1qBXCOhdZXShZjUDpdD85qTJY3wvbpyHGQyAjsMgorVx1J2aHVIY2JYf22SiecGDR6h6QI149NJ4ix5bffhm6rFpd/UycEz9pGoQgYI97KKe+fqM=,iv:TwMR4KeXsLgWAg5E8S2mBNxkiTWBM/vCCPjGpWbfHLA=,tag:9IawtvC1DA31zGoyDpiDIw==,type:str]
    pgp:
        - created_at: "2023-06-27T12:46:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DO8XyRaEk3R4SAQdApa+KXSYfT4nNQaKZ51y1vS64JE4+C3jt5JgaHPCxXxkw
            BY8Uq+hyUvtCiw1Z4QP/9nrcyLmDOAG/Dl+W2oezWksjupuvy1Vwz5EgmanSDyHZ
            0l4Bi9OXbmaC/T29e588bknfp+lGCp8KZ9nGNcfip5r89waMh9Sy8G26gyQkyQcC
            ihkLWCkdB7diGimNneK21S6UnEqn0pUliv3Co22ErCbD+ouuuiuFS5cuOmcp8045
            =GZ8L
            -----END PGP MESSAGE-----
          fp: BD995FEE3775172B56BF652CF10FF7F3F7265919
        - created_at: "2023-06-27T12:46:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4Dw5+PhuNaN4USAQdA1J9MRyFfanuZvfd9VoGufTCEd6QXJ4N+E6suA8bFJWAw
            8PmEZjXMXicqvdfVhn4n3NibEWpyJtf37fYwS1z/YxTqwqZaLq50grxJmB5sZWAK
            0l4B+hE2xZbYZRUdjplToaopeKZWXnhHpIpta/gYkZypYks/rXazPIUFmXUNCCbY
            yJ1VgC8STE8EzzuBfG7tMf9XzoLf13FPg/TGXRU39OPJmCdElmSyl9SHmNfBtdoY
            =UVcc
            -----END PGP MESSAGE-----
          fp: 7668061D49BB2B7BA19118B4031734BEBE51F818
        - created_at: "2023-06-27T12:46:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4D4cApnFfIi24SAQdAsYFI8+gyIZgKRakym1rQBtPhtD1FaZGItHjw0FJCCjYw
            ob7Dgx80v0C/n6unI7YpQXq5PmHNT37El1g1mIx8GvWxUBWjsO9a/BAvKF5n6Y3v
            0l4BbHvzw4kTPzYtJWEZtn7CX4d9Z9lV38rRlEcnqH0kcr5B9EwkRKu6nbl+AO/g
            ssBgPpILIB+ESE59mzRMaSk/WHjVfDeNhv+sBX6MzdJH656Yr9kK3/OYkx3bFtIP
            =Bo53
            -----END PGP MESSAGE-----
          fp: 67DB96C4F1D4F08F456697CC7668FD88C76CA761
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
