apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-postgresql
  namespace: harbor-registry
spec:
  instances: 1
  bootstrap:
    initdb:
      database: registry
      owner: bn_harbor
      secret:
        name: harbor-secrets-postgres
  storage:
    size: 8Gi
