# manifests/infrastructure/harbor-registry/harbor-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secrets
  namespace: harbor-registry
type: Opaque
stringData:
  HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:UyrDuitdXdQtxFbC9SxPKorpZlotM0FOFQrnSCipeao=,iv:VDA0gjznwADoN3jaYrD7TsqKedH0eiUTxvkHlyFth+s=,tag:TM0Slgxw+jbvuch2XBt2Sg==,type:str]
  POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:YPB/qwbjemG6Hsiro1gqBsIXoOAVhSIZ0147Ew==,iv:KAGd4ziT8sYgVTAC6+oTNue3auIr2rquyl+fnydaQCg=,tag:/OeuvSYj3Q795p+6xTCphA==,type:str]
  HARBOR_DATABASE_PASSWORD: ENC[AES256_GCM,data:1zeqKm+P2rXjuzZE791ysFJBjJmt1l1Jsm6/ew==,iv:gSsKt0RsdyguZkEsgud5gcFcBiU8Zk0C0pNIjUy012w=,tag:YtfqtVCpKTl74LayDTsXxw==,type:str]
  postgres-password: ENC[AES256_GCM,data:1VEGEzi9xU5RGbRyIuQwakUrjSk0D57qsS99ew==,iv:dbngT8k7DkrpOCpCA4sVzENdlcEhZUrQgXybjyow604=,tag:FVOCQqwSfLnQ37hDWVkr1g==,type:str]
  _REDIS_URL_CORE: ENC[AES256_GCM,data:m/B9Bh5R/3etXuSsqKV+maBdsLyW7Rnah2YhohLvQmVt8Q==,iv:6iXae7TNqzQ5pE2xATOL5FsP9auVuI6geGlFklFwyEI=,tag:NprXrfLKMtmfkx0acc1MwA==,type:str]
  _REDIS_URL_REG: ENC[AES256_GCM,data:V3GtdNHZLyCBaRbtSCA8V/wpteDL0m+bNAs2SYjmHkf7wA==,iv:f6CS31aJBH/OW5nWShpvKJUkTB+J+eNkH9movHBBwDQ=,tag:d/uxzhGY6HE1FuaagwARHw==,type:str]
sops:
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1STlOeUF4b1BtcWl0Nnlv
        WVAvNzRFdnVPc3k1aHJmdTg0NHJ3N2tSaXpvCit6azNuaU1qTWxhU3VTZTU5L0Ru
        bmYxSFdMNW9TSlh5Z2dseVdrcWJXMzAKLS0tIHpIdW5zVE91dVJUbWl0d0RXcW1u
        WGtsUm5ZYnJsckhCZkZwOUMwQmJNdGsK+7xMAcYTXTcMexIaU8viFE+QNLaITHOX
        V2Vg6lgnTeEquVelXkdhB1PwZMHXoANflk098OTTnHJrUAgSMblQCw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S1BPSDBNTmdrbXM1WGh4
        THYxaUJYU0dyMS94d3FhWldFVVNDZ04zclRjCnVmQmZrbUJmTGpQZUt5OW5KeXhl
        c0hxcmswa1p2eWRBM1Jkc29MOGY1Qm8KLS0tIE5nbUNRdnc2TEZQWSt6eGkxaVFS
        dG5BRzB3TFo3MlNCc25qVjZUTCswSDgKwA0GzQ4ZhVXrhQlZHtIoi/l+nX4Cl+NQ
        KWI90I8cJ97CkVUvjjn4T8NGL5fLwGMchOiawtUCT0cpevwca76Oyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-24T21:54:00Z"
  mac: ENC[AES256_GCM,data:GG/BAJraZ8t8F1i2yiSft0rrfzi97kH2hbkXDQiaBN+m1ZPTuMqH675hnezXX0pSpxS0CNMvbYJ8Iz1dw9+iltLzwzFtzkU8m5t/9KB/ljEwvvc6Px8Jp4CAHeWgTR+iIolSHOxd716/a6MG2FtwyIqptxg1v1yKGr0Z17x6kj0=,iv:8UWHvUGTgAlCcyOuPdwoFCcVvjF4FctH2FYHWBvCKgA=,tag:QH9a33J1HW6Q7NSmcrQsKg==,type:str]
  encrypted_regex: ^(data|stringData|Authorization)$
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secrets-postgres
  namespace: harbor-registry
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:PaJh1nxu72Pe,iv:5D152mIvgiMgphVEsa81u8bqj3Rw0RHXrHfWTK128BU=,tag:6WJHcYD0h7mNLAJTX2C4wA==,type:str]
  password: ENC[AES256_GCM,data:KEcy6htYMrjs4mV3Q0YNYQthZY/SCuakAB1mhQ==,iv:ok7QXVXSw7ktPkTnS4S3XbIKdyXDjDWG4/CJbOAf40w=,tag:NnMoNItNo7no9SuSGKNPYg==,type:str]
sops:
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1STlOeUF4b1BtcWl0Nnlv
        WVAvNzRFdnVPc3k1aHJmdTg0NHJ3N2tSaXpvCit6azNuaU1qTWxhU3VTZTU5L0Ru
        bmYxSFdMNW9TSlh5Z2dseVdrcWJXMzAKLS0tIHpIdW5zVE91dVJUbWl0d0RXcW1u
        WGtsUm5ZYnJsckhCZkZwOUMwQmJNdGsK+7xMAcYTXTcMexIaU8viFE+QNLaITHOX
        V2Vg6lgnTeEquVelXkdhB1PwZMHXoANflk098OTTnHJrUAgSMblQCw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S1BPSDBNTmdrbXM1WGh4
        THYxaUJYU0dyMS94d3FhWldFVVNDZ04zclRjCnVmQmZrbUJmTGpQZUt5OW5KeXhl
        c0hxcmswa1p2eWRBM1Jkc29MOGY1Qm8KLS0tIE5nbUNRdnc2TEZQWSt6eGkxaVFS
        dG5BRzB3TFo3MlNCc25qVjZUTCswSDgKwA0GzQ4ZhVXrhQlZHtIoi/l+nX4Cl+NQ
        KWI90I8cJ97CkVUvjjn4T8NGL5fLwGMchOiawtUCT0cpevwca76Oyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-24T21:54:00Z"
  mac: ENC[AES256_GCM,data:GG/BAJraZ8t8F1i2yiSft0rrfzi97kH2hbkXDQiaBN+m1ZPTuMqH675hnezXX0pSpxS0CNMvbYJ8Iz1dw9+iltLzwzFtzkU8m5t/9KB/ljEwvvc6Px8Jp4CAHeWgTR+iIolSHOxd716/a6MG2FtwyIqptxg1v1yKGr0Z17x6kj0=,iv:8UWHvUGTgAlCcyOuPdwoFCcVvjF4FctH2FYHWBvCKgA=,tag:QH9a33J1HW6Q7NSmcrQsKg==,type:str]
  encrypted_regex: ^(data|stringData|Authorization)$
  version: 3.10.2
