# manifests/infrastructure/harbor-registry/harbor-registry.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor-registry
  namespace: harbor-registry
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor-registry
  namespace: harbor-registry
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: "<25.0.0"
      sourceRef:
        kind: HelmRepository
        name: harbor-registry
        namespace: harbor-registry
      interval: 1m
  values:
    clusterDomain: local.kronform.pius.dev
    externalURL: https://registry.kronform.pius.dev
    adminPassword: changeme
    persistence:
      persistentVolumeClaim:
        registry:
          size: 200Gi
    core:
      updateStrategy:
        type: Recreate
    jobservice:
      updateStrategy:
        type: Recreate
    registry:
      updateStrategy:
        type: Recreate
    exposureType: ingress
    ingress:
      core:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hostname: registry.kronform.pius.dev
        tls: true
