# manifests/infrastructure/openobserve/fluentbit.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluentbit
  namespace: openobserve
spec:
  interval: 5m0s
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: openobserve
spec:
  interval: 5m
  chart:
    spec:
      chart: fluent-bit
      version: <0.46.6
      sourceRef:
        kind: HelmRepository
        name: fluentbit
        namespace: openobserve
      interval: 1m
  values:
    podAnnotations:
      fluentbit.io/exclude: "true"

    extraPorts:
      - port: 12345
        containerPort: 12345
        protocol: TCP
        name: talos

    config:
      service: |
        [SERVICE]
          Flush         5
          Daemon        Off
          Log_Level     warn
          Parsers_File  custom_parsers.conf

      inputs: |
        [INPUT]
          Name          tcp
          Listen        0.0.0.0
          Port          12345
          Format        json
          Tag           talos.*

        [INPUT]
          Name          tail
          Alias         kubernetes
          Path          /var/log/containers/*.log
          Parser        containerd
          Tag           kubernetes.*

        [INPUT]
          Name          tail
          Alias         audit
          Path          /var/log/audit/kube/*.log
          Parser        audit
          Tag           audit.*

      filters: |
        [FILTER]
          Name                kubernetes
          Alias               kubernetes
          Match               kubernetes.*
          Kube_Tag_Prefix     kubernetes.var.log.containers.
          Use_Kubelet         Off
          Merge_Log           On
          Merge_Log_Trim      On
          Keep_Log            Off
          K8S-Logging.Parser  Off
          K8S-Logging.Exclude On
          Annotations         Off
          Labels              On

        [FILTER]
          Name          modify
          Match         kubernetes.*
          Add           source kubernetes
          Remove        logtag

      customParsers: |
        [PARSER]
          Name          audit
          Format        json
          Time_Key      requestReceivedTimestamp
          Time_Format   %Y-%m-%dT%H:%M:%S.%L%z

        [PARSER]
          Name          containerd
          Format        regex
          Regex         ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
          Time_Key      time
          Time_Format   %Y-%m-%dT%H:%M:%S.%L%z

      outputs: |
        [OUTPUT]
          Name                 opentelemetry
          Match                *
          Host                 openobserve-collector-gateway-collector
          Port                 4418
          Log_response_payload True
          Tls                  On
          Tls.verify           Off
          logs_body_key $message
          logs_span_id_message_key span_id
          logs_trace_id_message_key trace_id
          logs_severity_text_message_key loglevel
          logs_severity_number_message_key lognum

    daemonSetVolumes:
      - name: varlog
        hostPath:
          path: /var/log

    daemonSetVolumeMounts:
      - name: varlog
        mountPath: /var/log

    tolerations:
      - operator: Exists
        effect: NoSchedule
