apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: openobserve-collector-gateway
  namespace: openobserve
spec:
  config:
    connectors:
      servicegraph:
        dimensions:
          - http.method
        latency_histogram_buckets:
          - 1
          - 2
          - 3
          - 4
          - 5
        store:
          max_items: 10
          ttl: 1s
      spanmetrics:
        aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
        dimensions:
          - default: GET
            name: http.method
          - name: http.status_code
        dimensions_cache_size: 1000
        exemplars:
          enabled: true
        histogram:
          explicit:
            buckets:
              - 100us
              - 1ms
              - 2ms
              - 6ms
              - 10ms
              - 100ms
              - 250ms
              - 500ms
              - 1000ms
              - 1400ms
              - 2000ms
              - 5s
              - 10s
              - 30s
              - 60s
              - 120s
              - 300s
              - 600s
        metrics_flush_interval: 15s
    exporters:
      otlphttp/openobserve:
        endpoint: http://openobserve-openobserve-standalone.openobserve.svc.local.kronform.pius.dev:5080/api/default/
        headers:
          Authorization: ENC[AES256_GCM,data:K4Z6xZIBpHkWT0maUysmZDdbhbwjE36Ra8IlAKvH/OSV2PE67c7rEiv9FA4uaNPYM6sFotfmmzbnWg==,iv:7Muuf8JEymzyptdBbILA95RG+RRixgnR5k5dCaznd5g=,tag:vX6aJkukN7kWuRqrBNN06g==,type:str]
          stream-name: default
      otlphttp/openobserve_k8s_events:
        endpoint: http://openobserve-openobserve-standalone.openobserve.svc.local.kronform.pius.dev:5080/api/default/
        headers:
          Authorization: ENC[AES256_GCM,data:hIOdU7U+X4waUGVH+R7eJr8gZND+gN45BaUof6B1nhvY5oCQolSmoFOCiTavysAL3yxaDqjKhRiEUw==,iv:imHnQeM7k9R4irN6WjBa8bh3hzWnb5E5qdyxlmV8Cbs=,tag:u86KuOR76vaiaSvjHZ0q5A==,type:str]
          stream-name: k8s_events
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
      k8sattributes:
        auth_type: serviceAccount
        extract:
          labels:
            - from: pod
              key: app.kubernetes.io/name
              tag_name: service.name
            - from: pod
              key: k8s-app
              tag_name: service.name
            - from: pod
              key: app.kubernetes.io/instance
              tag_name: k8s.app.instance
            - from: pod
              key: app.kubernetes.io/version
              tag_name: service.version
            - from: pod
              key: app.kubernetes.io/component
              tag_name: k8s.app.component
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.node.name
            - k8s.pod.start_time
            - k8s.deployment.name
            - k8s.replicaset.name
            - k8s.replicaset.uid
            - k8s.daemonset.name
            - k8s.daemonset.uid
            - k8s.job.name
            - k8s.job.uid
            - k8s.container.name
            - k8s.cronjob.name
            - k8s.statefulset.name
            - k8s.statefulset.uid
            - container.image.tag
            - container.image.name
            - k8s.cluster.uid
        passthrough: false
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
              - from: resource_attribute
                name: k8s.node.name
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
          - sources:
              - from: connection
      resourcedetection:
        detectors:
          - env
        override: true
        timeout: 2s
    receivers:
      k8s_cluster:
        allocatable_types_to_report:
          - cpu
          - memory
          - storage
        collection_interval: 30s
        metrics:
          k8s.container.cpu_limit:
            enabled: false
          k8s.container.cpu_request:
            enabled: false
          k8s.container.memory_limit:
            enabled: false
          k8s.container.memory_request:
            enabled: false
        node_conditions_to_report:
          - Ready
          - MemoryPressure
          - DiskPressure
          - PIDPressure
      k8s_events:
        auth_type: serviceAccount
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - field_selector: status.phase=Running
            interval: 15m
            mode: pull
            name: pods
          - group: events.k8s.io
            mode: watch
            name: events
      otlp:
        protocols:
          grpc: {}
          http: {}
      otlp/logs:
        protocols:
          http:
            endpoint: 0.0.0.0:4418
      prometheus:
        config:
          scrape_configs: []
    service:
      pipelines:
        logs/fluentbit-forward:
          exporters:
            - otlphttp/openobserve
          processors:
            - batch
          receivers:
            - otlp/logs
        logs/k8s_events:
          exporters:
            - otlphttp/openobserve_k8s_events
          processors:
            - batch
            - k8sattributes
            - resourcedetection
          receivers:
            - k8s_events
        metrics:
          exporters:
            - otlphttp/openobserve
          processors:
            - batch
            - k8sattributes
            - resourcedetection
          receivers:
            - k8s_cluster
            - spanmetrics
            - servicegraph
        traces:
          exporters:
            - otlphttp/openobserve
            - spanmetrics
            - servicegraph
          processors:
            - batch
            - k8sattributes
            - resourcedetection
          receivers:
            - otlp
  daemonSetUpdateStrategy: {}
  deploymentUpdateStrategy: {}
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.113.0
  ingress:
    route: {}
  managementState: managed
  mode: statefulset
  observability:
    metrics: {}
  podDisruptionBudget:
    maxUnavailable: 1
  replicas: 1
  resources: {}
  serviceAccount: openobserve-collector
  targetAllocator:
    allocationStrategy: consistent-hashing
    enabled: true
    filterStrategy: relabel-config
    observability:
      metrics: {}
    podDisruptionBudget:
      maxUnavailable: 1
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      scrapeInterval: 30s
      serviceMonitorSelector: {}
    replicas: 1
    resources: {}
    serviceAccount: openobserve-collector
  upgradeStrategy: automatic
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RVEraGlnOUJyTk9wRmlI
        Ym5zWGdCcE9OakhwWmJHNmxoeWdxbGhxem1JCk55VjVMU2tkTk5ZMVJ1ckhoS3VR
        ZjVJMEUzR283TWpIZnV0UUI0T21nRTgKLS0tIHhxdWxCaWtVbk4xNjB0NlJWamx0
        dWx1bG1pbHVoVFBHZEVvb21DcEE2TDQKedAM/CNEGDZN0YOXLaTKPSxTqpWObmTq
        6pojel/n7TCx9bwSXOFXBO2CHrlpm6hl5hwJRVM1DvSn6Gr6YOmf6w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVCtRN1dRTmNqOHJEVEw2
        aVhFVllPZmRKU2MzdngzSjE2dHdxeXZ3TWdVCkdCNHZhY0ZVRzlPRUc0c0NISXo3
        dk1WSzBkbGhTcXhNb3ZCbklUd1VRTkkKLS0tIGpPdDczRktDNmNLZmF3dWRlNmJJ
        aVJLNkZDNEJoMjg2WlFONUVzWU5qcWsKMg68z42k7P6ofdFSIaY033cYu+ULBKJO
        JUxkwju1MPuaisZhCbBDhIQBJX7m4vM0njuB/0Hbp7y85O9DrCcn/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-11-08T23:20:06Z"
  mac: ENC[AES256_GCM,data:kR6ZqonvpymDPdNi3UEVLgn0zI7KE6XORXQXN0J2cIM4C7mfMf4Ur515lxSi05PjQpx6XzcieeLlYWFz3XxMkG5UF4kMLFHy2eNQcUfTGtzCWxWm7Cvk6mbBaeoQx5Sa1VlZdIJZZBvUla+zeNNx056dECn65OY2vLp7f5nY3o8=,iv:/OfykKB85c47AQqyBaoqrf31wGlO/GpTKG+6qQog4Ds=,tag:xCwXFsa59Xs5SuZER1WF6g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|Authorization)$
  version: 3.8.1
