apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: openobserve-collector-gateway
  namespace: openobserve
spec:
  config:
    connectors:
      servicegraph:
        dimensions:
          - http.method
        latency_histogram_buckets:
          - 1
          - 2
          - 3
          - 4
          - 5
        store:
          max_items: 10
          ttl: 1s
      spanmetrics:
        aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
        dimensions:
          - default: GET
            name: http.method
          - name: http.status_code
        dimensions_cache_size: 1000
        exemplars:
          enabled: true
        histogram:
          explicit:
            buckets:
              - 100us
              - 1ms
              - 2ms
              - 6ms
              - 10ms
              - 100ms
              - 250ms
              - 500ms
              - 1000ms
              - 1400ms
              - 2000ms
              - 5s
              - 10s
              - 30s
              - 60s
              - 120s
              - 300s
              - 600s
        metrics_flush_interval: 15s
    exporters:
      otlphttp/openobserve:
        endpoint: http://openobserve-openobserve-standalone.openobserve.svc.local.kronform.pius.dev:5080/api/default/
        headers:
          Authorization: ENC[AES256_GCM,data:QGYGTw4OowejDOb/iaIE4iCWmyA3lWaRe5l9HdbAwGexEvyYYK4VJNnaBOrZOlRqz7pUOLyxqajLAw==,iv:RX/2+xCqhAs/rRqT+N4H+7mw1g4u12ToYCY0yQi8ySM=,tag:aVnwze7dWCoYcEDHaBA6iA==,type:str]
      otlphttp/openobserve_k8s_events:
        endpoint: http://openobserve-openobserve-standalone.openobserve.svc.local.kronform.pius.dev:5080/api/default/
        headers:
          Authorization: ENC[AES256_GCM,data:EkUxQVwUAwDS/+I+qughDjREKtahRjXBzSXyTLpLPLOo8ifks6D+j/kfvoj7YNmTo5dOlW7EIWEs2Q==,iv:GRFaic/J42jb31npyVM6ZoTtSCcC9hSqG2GYahPQLqk=,tag:65JVRRX4xOhaDo+3CtmXGw==,type:str]
          stream-name: k8s_events
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
      k8sattributes:
        auth_type: serviceAccount
        extract:
          labels:
            - from: pod
              key: app.kubernetes.io/name
              tag_name: service.name
            - from: pod
              key: k8s-app
              tag_name: service.name
            - from: pod
              key: app.kubernetes.io/instance
              tag_name: k8s.app.instance
            - from: pod
              key: app.kubernetes.io/version
              tag_name: service.version
            - from: pod
              key: app.kubernetes.io/component
              tag_name: k8s.app.component
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.node.name
            - k8s.pod.start_time
            - k8s.deployment.name
            - k8s.replicaset.name
            - k8s.replicaset.uid
            - k8s.daemonset.name
            - k8s.daemonset.uid
            - k8s.job.name
            - k8s.job.uid
            - k8s.container.name
            - k8s.cronjob.name
            - k8s.statefulset.name
            - k8s.statefulset.uid
            - container.image.tag
            - container.image.name
            - k8s.cluster.uid
        passthrough: false
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
              - from: resource_attribute
                name: k8s.node.name
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
          - sources:
              - from: connection
      resourcedetection:
        detectors:
          - env
        override: true
        timeout: 2s
    receivers:
      k8s_cluster:
        allocatable_types_to_report:
          - cpu
          - memory
          - storage
        collection_interval: 30s
        metrics:
          k8s.container.cpu_limit:
            enabled: false
          k8s.container.cpu_request:
            enabled: false
          k8s.container.memory_limit:
            enabled: false
          k8s.container.memory_request:
            enabled: false
        node_conditions_to_report:
          - Ready
          - MemoryPressure
          - DiskPressure
          - PIDPressure
      k8s_events:
        auth_type: serviceAccount
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - field_selector: status.phase=Running
            interval: 15m
            mode: pull
            name: pods
          - group: events.k8s.io
            mode: watch
            name: events
      otlp:
        protocols:
          grpc: {}
          http: {}
      otlp/logs:
        protocols:
          grpc: {}
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs: []
    service:
      pipelines:
        logs/fluentbit-forward:
          exporters:
            - otlphttp/openobserve
          processors:
            - batch
          receivers:
            - otlp/logs
        logs/k8s_events:
          exporters:
            - otlphttp/openobserve_k8s_events
          processors:
            - batch
            - k8sattributes
            - resourcedetection
          receivers:
            - k8s_events
        metrics:
          exporters:
            - otlphttp/openobserve
          processors:
            - batch
            - k8sattributes
            - resourcedetection
          receivers:
            - k8s_cluster
            - spanmetrics
            - servicegraph
        traces:
          exporters:
            - otlphttp/openobserve
            - spanmetrics
            - servicegraph
          processors:
            - batch
            - k8sattributes
            - resourcedetection
          receivers:
            - otlp
  daemonSetUpdateStrategy: {}
  deploymentUpdateStrategy: {}
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.100.0
  ingress:
    route: {}
  managementState: managed
  mode: statefulset
  observability:
    metrics: {}
  podDisruptionBudget:
    maxUnavailable: 1
  replicas: 1
  resources: {}
  serviceAccount: openobserve-collector
  targetAllocator:
    allocationStrategy: consistent-hashing
    enabled: true
    filterStrategy: relabel-config
    observability:
      metrics: {}
    podDisruptionBudget:
      maxUnavailable: 1
    prometheusCR:
      enabled: true
      podMonitorSelector: {}
      scrapeInterval: 30s
      serviceMonitorSelector: {}
    replicas: 1
    resources: {}
    serviceAccount: openobserve-collector
  upgradeStrategy: automatic
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YkMrRDFKM0JHWlZ4L3FX
        bG9ZY2s5RU5SaVUrYU92U2lSc1RMSkxhSkJjCk9qTHJNNFJFV25peHZyZUVQVmFa
        bDU5d2NCcGF3T3ZhdVBtcGxaMjAxdEkKLS0tIHQ0emx1VDNid0Q5RHlGY0FURXZ1
        cXh2Z1NBWXQrN3RiN1VpdHJ0SmpNNGMK92n+Lv/H0QzPpnXOubFJrPCNlcy0ugYT
        eTF6bSc3pLIH3cH/OUYF/PJqWxt6uJHTGd21uyXkcN966GzjuP8xTQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSM2FWcWg5MGZCODBrcVAw
        N0JsM1pjbkdvbVhqVS9Kck92SmNrbFVzclh3ClFKbnVoa1ZpdzNEMnlZUUJTbTZE
        dk0rNlo4T2t3dVMvMndGVmx3VGRUc2MKLS0tIGZOSGM0a2cvL1VJaGp0Y01YYk9m
        dU05SHdjcU9SRnJkN09xbUlGYTh2eE0K/O1gnA6DUbzCpZ7yuRV8iDGDBz0m2KcZ
        YdzNWsbMXsl00iz1SFBb9AnA5n7npb6OvV8oaxdjZOsL1gvSZ0vS9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-15T23:30:28Z"
  mac: ENC[AES256_GCM,data:/oyQvivyzRc0n1lqEGXU+1ALJ7G/mqQRITFVoKQg35HfX/D7XJknxqc/MMVTppDBxi2Q36z4Tp5GYVxKTe2LYvH4ZSa9I+R0LV3P2j7yVpqQsAxRhrvITmk8BRC+U8eJn2QKP5XTE8mCNXYdR2nkFkSXN/yT1xeE4xUEtKkTiHE=,iv:jRWPrThOp5YPkvEVi0uQgFiG/UvXC+JFuWjcbL6F3qg=,tag:l84BXDy5BL2ru7prbZMF3g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|Authorization)$
  version: 3.8.1
