# manifests/infrastructure/openobserve/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - openobserve.yaml
  - prometheus-operator-crds.yaml
  - agent-collector.yaml
  - gateway-collector.yaml
  - collector-sa.yaml
  - https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.99.0/opentelemetry-operator.yaml
  - fluentbit.yaml
