# manifests/infrastructure/openobserve/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - openobserve.yaml
  - agent-collector.yaml
  - gateway-collector.yaml
  - collector-sa.yaml
  - opentelemetry-operator.yaml
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.82.2/bundle.yaml
