# manifests/infrastructure/openobserve/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.yaml
  - openobserve.yaml
  - agent-collector.yaml
  - gateway-collector.yaml
  - collector-sa.yaml
  - https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.99.0/opentelemetry-operator.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/tags/v0.74.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/tags/v0.74.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
