# manifests/infrastructure/openobserve/openobserve.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openobserve
  namespace: openobserve
spec:
  interval: 5m0s
  url: https://charts.openobserve.ai
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RUVRMmMrRm03TzZzYmt5
        bTZnb0ljVVFWWllLQytRSE5oejZ3VUFhdnprCjU4RHRpOStPeUsrUmZjTnN1aGJH
        Qk1yZnEyOUh0SVgxdUdKdy9tajQ1Q3MKLS0tIENIMHFBbGZPMjRvOTBSZzFEOGJh
        S0N1bEtiOWd0OEtXZVNkQUcvUWhtYkEKdJhfKYyVMzydupZ2kGjPH/0avabv59lJ
        HNSII2knRHiY/QRLAZLABtJE/hy2hz4Hp2cyvzC8uQ5TqZ2RNk7CMg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZXJKL1RsMDgyc3UwTU56
        WHZ3Zm1kL0FTZE9La1RjeEdZOW1WWU01djM4CmRraWxLVTNrWFNKWlVlQ1k3WnI1
        NnVwZXc4WHAxL2xMWUpQSWVEZ0xkQjAKLS0tIEhGNUY5TjRWQWxjWXFrcjFMRVR6
        RzVCQWl0dzA3ZFV4c3J1TlJ2VXZsRVkKBUBSGcgw90WhQfK/uyZSErU9A0dYswXr
        L8diQSwiGi3gbm6VV2hYdYlB7/NEfwdVSPfiOAaNR7+Kr2lJoARHSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-18T09:38:46Z"
  mac: ENC[AES256_GCM,data:SOK6yWoQXB9x80RFTSzHxn5LA1N+ytdFf2+y4OYmGgNXjIT94MCK984TdUWzoLuCBntwM7UBmuj65Q1rK6lkXzR9TM539/5gvoMYcgHLAlRolohOl9SH8pHGAd23M87oI9RCoTOqLwpwYm3IkkUTchF3/fO45F/vvqUdjBpxeZY=,iv:CrCF6HABQiT6sJCFNY6OQySBplraOuoRcy4Mj6kFZLw=,tag:jQ0aLmLoCbzcGJYyUWsdvA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|Authorization)$
  version: 3.8.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openobserve
  namespace: openobserve
spec:
  interval: 5m
  chart:
    spec:
      chart: openobserve-standalone
      version: <0.11.0
      sourceRef:
        kind: HelmRepository
        name: openobserve
        namespace: openobserve
      interval: 1m
  values:
    config:
      ZO_TELEMETRY: "false"
      ZO_TELEMETRY_URL: http://127.0.0.1
      ZO_WEB_URL: https://obs.kronform.pius.dev
    persistence:
      size: 300Gi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: null
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/enable-cors: "true"
      hosts:
        - host: obs.kronform.pius.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: obs.kronform.pius.dev-tls
          hosts:
            - obs.kronform.pius.dev
    extraEnv:
      - name: ZO_ROOT_USER_EMAIL
        valueFrom:
          secretKeyRef:
            name: openobserve-credentials
            key: ZO_ROOT_USER_EMAIL
      - name: ZO_ROOT_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: openobserve-credentials
            key: ZO_ROOT_USER_PASSWORD
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RUVRMmMrRm03TzZzYmt5
        bTZnb0ljVVFWWllLQytRSE5oejZ3VUFhdnprCjU4RHRpOStPeUsrUmZjTnN1aGJH
        Qk1yZnEyOUh0SVgxdUdKdy9tajQ1Q3MKLS0tIENIMHFBbGZPMjRvOTBSZzFEOGJh
        S0N1bEtiOWd0OEtXZVNkQUcvUWhtYkEKdJhfKYyVMzydupZ2kGjPH/0avabv59lJ
        HNSII2knRHiY/QRLAZLABtJE/hy2hz4Hp2cyvzC8uQ5TqZ2RNk7CMg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZXJKL1RsMDgyc3UwTU56
        WHZ3Zm1kL0FTZE9La1RjeEdZOW1WWU01djM4CmRraWxLVTNrWFNKWlVlQ1k3WnI1
        NnVwZXc4WHAxL2xMWUpQSWVEZ0xkQjAKLS0tIEhGNUY5TjRWQWxjWXFrcjFMRVR6
        RzVCQWl0dzA3ZFV4c3J1TlJ2VXZsRVkKBUBSGcgw90WhQfK/uyZSErU9A0dYswXr
        L8diQSwiGi3gbm6VV2hYdYlB7/NEfwdVSPfiOAaNR7+Kr2lJoARHSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-18T09:38:46Z"
  mac: ENC[AES256_GCM,data:SOK6yWoQXB9x80RFTSzHxn5LA1N+ytdFf2+y4OYmGgNXjIT94MCK984TdUWzoLuCBntwM7UBmuj65Q1rK6lkXzR9TM539/5gvoMYcgHLAlRolohOl9SH8pHGAd23M87oI9RCoTOqLwpwYm3IkkUTchF3/fO45F/vvqUdjBpxeZY=,iv:CrCF6HABQiT6sJCFNY6OQySBplraOuoRcy4Mj6kFZLw=,tag:jQ0aLmLoCbzcGJYyUWsdvA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|Authorization)$
  version: 3.8.1
