# manifests/infrastructure/openobserve/openobserve.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openobserve
  namespace: openobserve
spec:
  interval: 5m0s
  url: https://charts.openobserve.ai
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQzZ1c05tL1FCUU9meGEw
        SkZORWJhQWpNNEhqemRNSC94K0JLUVFpYjFzCkpva1FFb2JpMlRKbkZRZHB1M0h0
        RlVTU1ZkZ05wUXpBZjhqUTVuakxzeXcKLS0tIDVQbkFCYnBCeWNKNEl6Sko4RTgz
        VEVUNmtLUUNhSFk0WFhFN3J5dHN6dXcKzY56AXGH+fdhm2INHwGZvsUQDF4spqGc
        n09eMk2ZUfDNUdP8vfgdIIExVbZHFwvCGxBcQsB8jWXlfL1XXrw0gw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUU5FQ0phVVdWWVN4V1lR
        ZnFMV3A5NFI3SzFRcEttbWNlbUV1dTYrOEFBCmJSM1lEaTdyM1UraXhMbjc2OElv
        V3NlZWlpdHp1Wi9PUElkeFk1Ukp0NGMKLS0tIHRCVk9TVjF5WDJsbkpmZEI5c3RZ
        TjQ5cmR3UXlSSHdCQ2RKREhHeDZKM2sK7MrPvuvDQTqU90e1BMHTF4vrhghGyyq5
        I06YRmDKaJpa5lPvPb9ETFdPgJz0eNV9KIlI7lOOjUgfC2RpKxcH9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-05T23:43:13Z"
  mac: ENC[AES256_GCM,data:VJTs9z4gXsVs0x6COZUL0CV9IWANGRfHd8aCiAN5tcJFZR5JitdPR6pkw8kRB/AtkeqS6BJTCYJbLAYyHuLK4nyfZEls+ENLa1lKebezxL4U8jFAgnvHG4oSpDn5MCRDoXakIlvm/5irD0C0GyHcBhBWP0auSkm+VLunN2FhIFw=,iv:pIKn2HXJG8OtyTcqIe516kA1z7bdAtDaeU8m+ADL6wc=,tag:uN6HFfG2F1kNo5+Un6Fv2w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|Authorization)$
  version: 3.9.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openobserve
  namespace: openobserve
spec:
  interval: 5m
  chart:
    spec:
      chart: openobserve-standalone
      version: <0.11.0
      sourceRef:
        kind: HelmRepository
        name: openobserve
        namespace: openobserve
      interval: 1m
  values:
    config:
      ZO_TELEMETRY: "false"
      ZO_TELEMETRY_URL: http://127.0.0.1
      ZO_WEB_URL: https://obs.kronform.pius.dev
    persistence:
      size: 1000Gi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/issuer: null
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/enable-cors: "true"
      hosts:
        - host: obs.kronform.pius.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: obs.kronform.pius.dev-tls
          hosts:
            - obs.kronform.pius.dev
    extraEnv:
      - name: ZO_ROOT_USER_EMAIL
        valueFrom:
          secretKeyRef:
            name: openobserve-credentials
            key: ZO_ROOT_USER_EMAIL
      - name: ZO_ROOT_USER_PASSWORD
        valueFrom:
          secretKeyRef:
            name: openobserve-credentials
            key: ZO_ROOT_USER_PASSWORD
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQzZ1c05tL1FCUU9meGEw
        SkZORWJhQWpNNEhqemRNSC94K0JLUVFpYjFzCkpva1FFb2JpMlRKbkZRZHB1M0h0
        RlVTU1ZkZ05wUXpBZjhqUTVuakxzeXcKLS0tIDVQbkFCYnBCeWNKNEl6Sko4RTgz
        VEVUNmtLUUNhSFk0WFhFN3J5dHN6dXcKzY56AXGH+fdhm2INHwGZvsUQDF4spqGc
        n09eMk2ZUfDNUdP8vfgdIIExVbZHFwvCGxBcQsB8jWXlfL1XXrw0gw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUU5FQ0phVVdWWVN4V1lR
        ZnFMV3A5NFI3SzFRcEttbWNlbUV1dTYrOEFBCmJSM1lEaTdyM1UraXhMbjc2OElv
        V3NlZWlpdHp1Wi9PUElkeFk1Ukp0NGMKLS0tIHRCVk9TVjF5WDJsbkpmZEI5c3RZ
        TjQ5cmR3UXlSSHdCQ2RKREhHeDZKM2sK7MrPvuvDQTqU90e1BMHTF4vrhghGyyq5
        I06YRmDKaJpa5lPvPb9ETFdPgJz0eNV9KIlI7lOOjUgfC2RpKxcH9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-09-05T23:43:13Z"
  mac: ENC[AES256_GCM,data:VJTs9z4gXsVs0x6COZUL0CV9IWANGRfHd8aCiAN5tcJFZR5JitdPR6pkw8kRB/AtkeqS6BJTCYJbLAYyHuLK4nyfZEls+ENLa1lKebezxL4U8jFAgnvHG4oSpDn5MCRDoXakIlvm/5irD0C0GyHcBhBWP0auSkm+VLunN2FhIFw=,iv:pIKn2HXJG8OtyTcqIe516kA1z7bdAtDaeU8m+ADL6wc=,tag:uN6HFfG2F1kNo5+Un6Fv2w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|Authorization)$
  version: 3.9.0
