# manifests/infrastructure/openobserve/prometheus-operator-crds.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-operator
  namespace: openobserve
spec:
  interval: 1m0s
  ref:
    semver: "<0.74.0"
  url: https://github.com/prometheus-operator/prometheus-operator.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-pod-monitors
  namespace: openobserve
spec:
  interval: 10m0s
  path: ./example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: prometheus-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-service-monitors
  namespace: openobserve
spec:
  interval: 10m0s
  path: ./example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: prometheus-operator
