# manifests/infrastructure/openobserve/secret.yaml
apiVersion: v1
data:
  ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:JMGZcA9CkCm4PMzWDV2pJVSLRBk=,iv:FvHqOuU7X1rOu+mIvyeoPS8570sljU0RmT7YLY52ppc=,tag:nb8Fntp3wW0UqHg1D0O3Zg==,type:str]
  ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:68z12htARNc=,iv:PkedladUKHYBnqP8enaQg2irKet6LSK67jLZ/Qh5Zz0=,tag:tKBflIpgs9W20sTfvhrrlg==,type:str]
kind: Secret
metadata:
  name: openobserve-credentials
  namespace: openobserve
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGFoNVE2SCt3Y0dOdHk5
        cDV5cVRhNk5OOVlyb1dhV1UzYmlZMDRYbVc4CndRSld4ZVR5TjdVYUU3djVtZEtH
        YVVNNkc3a2drOGtHOTdPTjFhVW1WQ2MKLS0tIEQwUVZmZHRDN0xtNVhwNlI1RDNm
        cXdNWm5nTzQxS0hsUk5XRXplbG1wTWsKdLwm/QhUTXULj+eTMElJ27tsa/agE27K
        6lGFelHpTSjqNZY5gnhp6HrhhT0sQqoYkIDWKIXlJKnkxjgpV/X5Vg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYXZxUUN5eFA4d3IzdzFa
        MWxNUFh2MW90Y0RNbGhLdmQ0MjY5K0g0RjNNCkZ6c0UwOHFFV1hsY2pZbmhrTGlF
        b3hnUWtqVlZ1SnVoUTRRd01QQmxGNjgKLS0tIEFVWThmbFZUNDFodC8xWUl5MVIr
        OUxVdng5cDdYVXloWWVQZmFHSUFFTU0K1rAQr421XjnQx51AWBRQEAb8jUhGOESH
        uPexvUcIIroY+xP51+j0dir+l6V6WbbL/OxGrYrqxOdTAHoxLzaTtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-13T09:48:49Z"
  mac: ENC[AES256_GCM,data:M8GiisjTOdXlMDRciFVp4ULmLCzY+vCBzY7XlLcevNWMrMgJwyC9R3vwLFYkj2U/muuNcyI0HSGyvd0ajZOvs616vQzhWMw8AIYYJf5ussgTdWh7M91fpLJPqgu0+GQ7rbBemEFFNb4HdpsiDpBMgsW4DYiH1yHmYlDKz1HVNm4=,iv:0PE8nD+zKeH3XnzgG437s4SH3HS/IFKZEiNHWGItwPk=,tag:+lxJxxJFhsXYUk3GPNYw/Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
