# manifests/infrastructure/kamaji/kamaji.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kamaji
  namespace: kamaji-system
spec:
  interval: 5m0s
  url: https://clastix.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kamaji
  namespace: kamaji-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kamaji
      version: "0.15.1"
      sourceRef:
        kind: HelmRepository
        name: kamaji
        namespace: kamaji-system
      interval: 1m
  values:
    installCRDs: true
    etcd:
      deploy: false
    datastore:
      enabled: false
