apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUpKalQvajNnTGZVSG5Tdy95amg1RUl3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV4TURFeE9UVTJNamRhRncwek5URXdNekF4T1RVMgpNamRhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRuZ2t1Z0JKbEtjazFxTTUyVHV5VmMzbUYwWk1OSXBUamxJWGc2d3ZFR3JDcmpHbFJGU3RCQjB0UWkKbU1IcUh4Nkd0bExNcEhYRXJRMWdRRWVwV0svQW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGRnV1Zm5sRnN4RnFUYTgvbVB1eE01cGFZRGd1TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDMU9kN1AKenZRR0RkbWllY1VBa1VoQ0s1L2RGL2cxeXB6SXVvOEY0VTg3YmdJZ2ZSY1JmczU0eURGVGx0cUtVU3pTV3poQwo5a1hZejBKb1hLNGZQWTUzdVNBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://kronform-v2.pius.dev:6443
    name: kronform
contexts:
  - context:
      cluster: kronform
      namespace: default
      user: admin@kronform
    name: admin@kronform
current-context: admin@kronform
kind: Config
users:
  - name: admin@kronform
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVNxZ0F3SUJBZ0lRV3k5UityT1lVVEZGaThEUjNFNGNXekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNVEV3TXpFME1qQXpOMW9YRFRJMk1URXdNekUwTWpBMApOMW93S1RFWE1CVUdBMVVFQ2hNT2MzbHpkR1Z0T20xaGMzUmxjbk14RGpBTUJnTlZCQU1UQldGa2JXbHVNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFeHR0a3lERW9oTXArRGRYQk9mTi8xTGpkb3l1RVVjVVIKb2ppSVdvaEFqYTcvMWVVQkZQRW1ZY0hCK2kxVlVBN2duaVRaZGlhTkducW1UOGQ2Ylp4MlBLTklNRVl3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01COEdBMVVkSXdRWU1CYUFGRnV1CmZubEZzeEZxVGE4L21QdXhNNXBhWURndU1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRRG1mWU9VV29ZVEhpQ20KTVpjWkVLMXhnYUJ1Wi81MGpGaVJDeGdTN0Z1dW9nSWhBSUw2K0RXL1pmbHl1Rmg1OHEwU3VRM05yTERwNjBiMQorR3NrMWpPM3phMDUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      client-key-data: ENC[AES256_GCM,data:gImPyKsjRJumFt7lKZXr+1/v9R3QcwRn/QuZY49t84BURLXwvFOTDKzy5LKyau7Zuj2SMYm9OBBwsnBbEW1T0sXeu5emuxTzRAwmHxUla9ScsHKpSoHC14zx1u1iU+8s8K4oTIXyXRzGHdN6M6FHOspYsES5JNwmvcfnwPID66KXFdB54YYs6EWxmorUAYBPECqQECAfZHz2450ffOwxFrWkCIpH5fvWWYR2iH585T+ABABjqvFDS427vJeEFrWOu5GoMj77GdAY6NT2KyG1WMF7OqEBN4ZzPhTkdk6zEeVoX9b/uxbCOxa2lInj5IfawW/AppJcAr/3TnzauLdIZLsyB7REz2DxYYKyjXNXl1gq9hrEsZAr1gFigJJVny665kjV+dF2Uawcw912m3eeDA==,iv:Ad9QZvOsQqlut9blBUJ7TK4EN11zIX2Tqh6Og+8NVV4=,tag:jGECbLMGY9aPt0ry09sUgQ==,type:str]
sops:
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWHhpMUJhcUVWQ2VyMXlp
        Sk5QUDU3ZWcvSytuRmQ5TTVXUmNESnJDOGlFCjBaWUVTZDk3Q2lRdTNWbDFiOThD
        U2RiUU9SRnVwQ1JpWHFTeHRrb1NnRTgKLS0tIDFWVm5JSTNieUhZVnFJVG8wdWFp
        YUNuMHcrbEVRYTkvN0NMOGd5U3hqTmMKsqvJ/QXhuFJFxCOiVamZwU7dNnwocLOq
        YZa+v88NDfw/bxnsm9x6Z1AO5jcWcJIJ5pfbaq/10tRu3vHuedFHdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-03T14:20:47Z"
  mac: ENC[AES256_GCM,data:iIz4Z3asUmcG9uiUa7vcx2XjumU3pncIQM5ZTwcO5mP0lJyZ809YxkwGyy0qNC1NM8PQQrq9065ZYy0RgL3LBMMY+Kuj2txMRg66lkLGpIXhnoUJd682di3cEUXgQ4bDnfC7QFCUIkdGjmwlLjQDJ7oqOZccqcxoc2uk6AiM+6I=,iv:KySwziBC7oZfO2/kpgPUEWVUIVRC7p0g51jUOqjUd+w=,tag:70YPxZusZntPyyyQFLorXQ==,type:str]
  encrypted_regex: ^client-key-data$
  version: 3.11.0
