apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUpKalQvajNnTGZVSG5Tdy95amg1RUl3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV4TURFeE9UVTJNamRhRncwek5URXdNekF4T1RVMgpNamRhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRuZ2t1Z0JKbEtjazFxTTUyVHV5VmMzbUYwWk1OSXBUamxJWGc2d3ZFR3JDcmpHbFJGU3RCQjB0UWkKbU1IcUh4Nkd0bExNcEhYRXJRMWdRRWVwV0svQW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGRnV1Zm5sRnN4RnFUYTgvbVB1eE01cGFZRGd1TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDMU9kN1AKenZRR0RkbWllY1VBa1VoQ0s1L2RGL2cxeXB6SXVvOEY0VTg3YmdJZ2ZSY1JmczU0eURGVGx0cUtVU3pTV3poQwo5a1hZejBKb1hLNGZQWTUzdVNBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://kronform-v2.pius.dev:6443
    name: kronform
contexts:
  - context:
      cluster: kronform
      namespace: default
      user: admin@kronform
    name: admin@kronform
current-context: admin@kronform
kind: Config
users:
  - name: admin@kronform
    user:
      client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVNxZ0F3SUJBZ0lRYmFhTVRTbEpvdCtwZ1I2TGFLN0UzekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNVEV3TXpJeU1EQXlObG9YRFRJMk1URXdNekl5TURBegpObG93S1RFWE1CVUdBMVVFQ2hNT2MzbHpkR1Z0T20xaGMzUmxjbk14RGpBTUJnTlZCQU1UQldGa2JXbHVNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNVJjTlVRNGtyUHNkVGF2WDJ0MFp6VHM0d0xwK3ViNVcKTHZBWCt4YThzWDI2ODJEYkZEcitXdWxnN0N6N3BDd2pYQTFvOEc1YTZDcE9wQ3kvdjdzcUxhTklNRVl3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01COEdBMVVkSXdRWU1CYUFGRnV1CmZubEZzeEZxVGE4L21QdXhNNXBhWURndU1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRRG8yWUpVWlhBMCtUWXYKUDhDZnJCaC9XU1cvSDFyNHNqYlJXR1hmb25jNFRBSWhBSkZWNjJTd2pITDJKUFV4Q2tJTmprR3BGYmJ3L3RxQgpJckpvdTB2akRDQjEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      client-key-data: ENC[AES256_GCM,data:ucV8SI0b5KRUqrSZhBwE7Jp0Z4rSMkJ/ViW04VOOp2WAlZDHJJ4nGv+taIWQE/WYSyOr02ngg6Apzj4246bAjI1yxeoDenQ3SWG0ZuSZNiXriQK54XdNy/SrBs53m4YwlC7AMVQ+WvQyEgMI7cq9WNo3PDU4pTRHKM4ywsGYiSunXVCHGRB4hbiEwUJf8RFub81VEl2jx5nlfbodMYsNdJlkbo8J80tAui7eXS2+76mg054dCSCZcKdaRqZG8J7wYnxJ0HyyawNSlMTPVpYJu0xTyMwX3zfwMriC9Vo8TZfPNTbHkysTq800AEsxlhvw4S1lwdDvu7uMzDMXensFjQpQN5g/bYiANb+oqvsEaB8d1LLT+lbpFqUIjHslNjv5YMlPNM53o492VHlLGVqK8Q==,iv:I9QpQYcmL+qBUFE9Kyzx/mt/+RoqKy1UH50/+6gO/pM=,tag:0DztNQRcm5049YXayOwwTA==,type:str]
sops:
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbU1pd2l0aWk0L0ltMkdz
        cHJPOUhDVUVnSTMwWnY4cysvMjNvaEhWWWxBCldXdmxCNDhXUnBsZnQxcUw5dkRV
        RHg3OXdNMWlVSmlGRjJBcFBVOUduSGMKLS0tIFoyb1NuenFGYytpV0M4NlBTZE9D
        alR3Q1FkZ0VORlRmVzdsdmhoaElpOUkKFneNcsarlbe0UuBfryIwxQvkix87PNXb
        bdvOcXNf4TUi1Fm8ZNLyIRoJvl8RJvd4SHQYd0Y60LDNchi9scx3og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-03T22:00:36Z"
  mac: ENC[AES256_GCM,data:75F46vcAnIlrOTu1BgjbGXguRh/og1/mnM44AeTUyKdFjh41NMxgLlMW9pNbm7Zubkd3mkbc6Co61yaUvxV2mZKkhBIP3LUNDjJbcajJN55Ifm5eVnja9owNz6JffyRZMDE7PtFr8yiMrNhMitvdhe8w/gyDH0qKu85T+K7KTpQ=,iv:wQhnQTiaXeCexdur5aqArjy62tcdva8PDOHtVDFVqgo=,tag:scDgxco+i9AfJVjGNUP+lA==,type:str]
  encrypted_regex: ^client-key-data$
  version: 3.11.0
