context: kronform
contexts:
    kronform:
        nodes:
            - 192.168.110.60
        endpoints:
            - 192.168.110.60
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEJIeXMrTXlxQk9jWU4vNndZRDVnd2VNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5URXhNREV4T1RVMk1qZGFGdzB6TlRFd016QXhPVFUyTWpkYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBbnhheWRyRkZwL2Z3aFFPK0xwS0V2ck1KLzNMaUJJQVJsTnZnCml4ZXlnQWlqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVeHo2cWpod0JEc0g1SHIzMQo3SzB3YXBhUVR2RXdCUVlESzJWd0EwRUFvZ0xZZE04SW9rek9PNHBWWmNIaDhocFRyZDFLZmdFK3RIYXhxcmhnCkRSNmtvZFhESlVPL1I1ZjlQc1E4UDFyQkppclBvcGQxVnFja3VxWkdhNWx5RGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLVENCM0tBREFnRUNBaEVBcnMvY25uVkV1RzVGWmtIRUdyWTBjREFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXhNVEF4TVRrMU56VTBXaGNOTWpZeE1UQXhNVGsxTnpVMFdqQVRNUkV3RHdZRApWUVFLRXdodmN6cGhaRzFwYmpBcU1BVUdBeXRsY0FNaEFMYldPUzY0eThGdm5tWG9sSW55YVBpaGR4RmkyU1hrCkRUVTJFaWQxS2ZuZW8wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVV4ejZxamh3QkRzSDVIcjMxN0swd2FwYVFUdkV3QlFZREsyVndBMEVBaU1EaQpDckxmOTN6ZFpDRW1FM0RHRmdnNW1vVUNFamlGck9kZmVEUFJXK0tWRWtJUFNlYXcybDY4cjM0QWtEa3F4ekkxCmFHU3JWbmNtVmE4c1o2aExCUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: ENC[AES256_GCM,data:U5kgO9r40S+xnDX/IHICgeZsYoS8M4RKmGiU+HwBSgZZzbZG5QNp5qvzSWaJuEpuFGqrsFzeDmaiK0EL+dCa7A0772NoBDZOjglBYhczoctK6qM9TMxrBgF5yOv8Ui00kRJtXlgMlN2Dkcdpwan/IYQy3mLq0xeJiD2/2cLlbY5Y+wOk0tz+xBKQmBLLuziv76xUTowOz4cBtf9gxzxpt0vJkOaJ8if2vInYSgDzlsV/eDpR,iv:mnKvmzFX6NZbjnaBux6XDvw02EQJPoRzqZUNF4Ap3GU=,tag:NVwwd5ZKHR5n88LclZUGsw==,type:str]
sops:
    age:
        - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZVZpbGZhdTIybVcwSGtt
              WnhUendDOHlESjJuVmRPNVBWNklFZzZaSWo4CnVSTFhOZFRDbXk2UFByQTdhYVBn
              bU5NQTNOV3lET3ZOWExTS1duM1RJWDAKLS0tIEwySE1jdk9SVWRLTFdweklRRVc4
              QVNyeFJZWkZ6VTVXcWhZNlpEU2lpencK0H3FGgB4t1cYBLn6vjKedzpJdZoPzvPR
              fU4UVVp0gm16osHDA+5pPTDfpr6np26femeYO2MXmDLmcjczPSE9SA==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T14:14:54Z"
    mac: ENC[AES256_GCM,data:zhsA2nHr4xqylV07Qd3t8mqJcx9nD+WEiq+IGZbI5WwAe1Mqd7u9hCOhYvLiRhsTftg2ABuyi410GyNHUArdFwjq67tyMgdGGugQHg5rKyDkX4vRp20D4d5a1sy4mjo3aKGKdgsAUxuuPvI8X7GaKzMoPBdBX+dOq+6FxVDQvNs=,iv:PZm+n7tbZ4JUkSPjskR/wmY+QmuNVQ1Jfu77I0n97Pc=,tag:Xnz+nG4c2zs3u8c7sUYOBA==,type:str]
    encrypted_regex: ^key$
    version: 3.11.0
