# manifests/infrastructure/kubevirt/kube-ovn.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-on
  namespace: kubevirt
spec:
  interval: 5m0s
  url: https://kubeovn.github.io/kube-ovn/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-ovn
  namespace: kube-virt
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-ovn
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: kube-ovn
        namespace: kubevirt
      interval: 1m
  values:
    MASTER_NODES: "159.69.60.182,88.99.105.56,46.4.77.66"
    replicaCount: 3
    func:
      ENABLE_NP: false
    cni_conf:
      CNI_CONFIG_PRIORITY: "10"
      CNI_CONF_FILE: "/kube-ovn/10-kube-ovn.conflist"