# manifests/infrastructure/postgres/cloudnativepg.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: postgres-operator
spec:
  interval: 5m0s
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnativepg
  namespace: postgres-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: "<0.23.3"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: postgres-operator
      interval: 1m
