apiVersion: v1
data:
  HCLOUD_TOKEN: ENC[AES256_GCM,data:3KiwLi4dBe6W6HHqLPKNm45HD12eH+gUdvy+n+80dDs=,iv:FvBjdYBSm4zuzq8hrt3sZPlkrLoIgq1Rm4OgVObGqdw=,tag:aWIzPiB4LwfOnWkx3+NphA==,type:str]
kind: Secret
metadata:
  name: hcloud-token
  namespace: kubizone
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10v5jyc5ylreyltm32kfj57fmqle0aumxqvg9lp67r50cl8ynlsmq9kx7ez
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbTZIZSsxSG5BZmV4M3U4
        SlQwc1drcGlrVmxodmlsU2t6Ui9IZ1J4NjFVCmJsZ0FSREowSzlMVGd0bktVZFB5
        WjU2L2k3d3pDdi9wV2pnNmhtOFhldzgKLS0tIDdNME5KTFA5azVkeWZqSXhNY2dv
        QWhlZGhDMUhNVUVQVVpqWnVmZG9uTGcKMQ52LKd0jFdU+xHgYFqjVNFh/gR7yeJ2
        jhcL/YxMhDEF8stVmCGFpc6RRQU/GV3pkGv/49BUYXXuRpfhr6nBGQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c8rjkuv9px2gfyrlqn75ajhv26l8fdmeugcdegt237c20l8uc4wq6y9h6d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRC9vc3luS1JZSXVZZE5N
        MUpybTkvMFNEY1UwbWV3OGlMeG42cUloQUR3CmZZQ3JRUERKaWVIZ0NxS1ZBRlYr
        Y0lYVzdHaHZ2ZkQxVDdEUUNtMGdOcXMKLS0tIGxpUGx5aXgrUytsNFU0ZW5GdVN1
        SGhOWmJzN1BaVjdqMWFRTGlpanQ3RXMKgVjU4QDDCIJmdcZZEbsDd1KwpDqG4ENK
        uHx/YyjarbB42P8Bgho+ZKIPi82rX4y1YkJ6EMTt4wla07e2WnY7TA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-07-05T11:16:09Z"
  mac: ENC[AES256_GCM,data:Uom9iN1tJqPOGSaHcpraHfPETs1o0JoQG+ecwGads1lI/D6Jn5CCjEb270MQVBpubWS+ElntjLjusPJbNFdqY0UZ9zC6Yp+24qR+m6V4T8VtoLkb7pZE/lz4FUg5QgCThcmLE+P5NJeVYPGnqKRAIey5dUupZYvGEbPmAEMFKfE=,iv:ZZzxJ3c7LEmQXB4eF+rBwgDK3n5F2CU7B13Bpy9a1vE=,tag:d8kV74GlbarNJ8YkP74dEQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|Authorization)$
  version: 3.8.1
