---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: fluxcd-alert
  namespace: flux-system
spec:
  eventMetadata:
    summary: "FluxCD Error"
  providerRef:
    name: telegram-provider
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: "*"
      namespace: "*"
    - kind: Kustomization
      name: "*"
      namespace: "*"
    - kind: HelmRepository
      name: "*"
      namespace: "*"
    - kind: HelmRelease
      name: "*"
      namespace: "*"
