---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: fluxcd-alert
  namespace: notification
spec:
  summary: "FluxCD Error"
  providerRef:
    name: telegram-provider
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"